# Generated by Django 3.1.4 on 2021-01-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adminn',
            fields=[
                ('adminname', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='用户名')),
                ('adminpassword', models.CharField(max_length=32, verbose_name='密码')),
                ('adminemail', models.CharField(max_length=30, null=True, verbose_name='邮箱')),
            ],
        ),
    ]
